org: dbfoot
app: who-am-i-server-kr
console: true
service: who-am-i-server-kr

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  apiGateway:
    binaryMediaTypes:
      - 'image/png'
      - 'image/jpeg'
      - 'multipart/form-data'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
